import React from 'react';
import Link from 'next/link';
import ToolsBar from '../components/MainToolsBar';
import Employees from '../components/Employees';
import Head from 'next/head'
import Frame from '../components/Frame'


const employees = ({data}) => {
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Frame>
            <Employees data={data}/>
        </Frame>
    </>;
};

export default employees;
