import React, { useState } from 'react';
import Head from 'next/head'
import LandingPage from '../components/LandingPage'

const landingPage = () => {
    

    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <LandingPage/>
    </>;
};

export default landingPage;
